alert (`أهلا بك في موقعي الذي سيحسب درجاتك`)
let grade = prompt (`اكتب درجاتك بالأرقام`)

if ( grade <=  90 && grade >= 100 ) 
console.log (`لقد حصلت على امتياز`)
else if (grade <= 90 && grade <=80 )
consolw.log (`لقد حصلت على جيد جدا `)
else if (grade <=  80 && grade <=70 )
consolw.log (`لقد حصلت على جيد  `)
else if (grade <= 70 && grade <=60 )
consolw.log (`لقد حصلت على مقبول ا `)
else if (grade <= 60 && grade <=50 )
consolw.log (`لقد حصلت على ضعيف `)
else if (grade <50 )
console.log (راسب)